// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGrt5zqz-f2wHHkSHiAQSf5SA8t0u_oJw',
    appId: '1:1075573865798:android:dbe6158d6333d6b49df947',
    messagingSenderId: '1075573865798',
    projectId: 'pntecommerce-c6f0e',
    storageBucket: 'pntecommerce-c6f0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC19UrCNooqnRqTKQ8CK3Mc5pI5zdWlLGE',
    appId: '1:1075573865798:ios:df84da8e209b8a5d9df947',
    messagingSenderId: '1075573865798',
    projectId: 'pntecommerce-c6f0e',
    storageBucket: 'pntecommerce-c6f0e.appspot.com',
    iosClientId: '1075573865798-i3011tvc5rhtvt8fh6f65a3nc1fo3k7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomBoniAdmin',
  );
}
